### ISSUE TITLE
Chatroom

### ISSUE THREAD

**Issue by minecraftxiaohu** [minecraftxiaohu/TalkAboutSomething#1]
众所周知，GitHub可以聊天

**Comment by YINGRJ** [comment]
啊对对对

**Comment by minecraftxiaohu** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by YINGRJ** [comment]
没办法，不能用下划线

**Comment by YINGRJ** [comment]
我吐了我刚刚正在启动minecraft，结果我妈进来了，吓得我赶紧结束了Java进程

**Comment by minecraftxiaohu** [comment]
> 我吐了我刚刚正在启动minecraft，结果我妈进来了，吓得我赶紧结束了Java进程

az，可怜

**Comment by minecraftxiaohu** [comment]
> 没办法，不能用下划线

那你可以用减号

**Comment by YINGRJ** [comment]
邮箱会收到怎么办 我妈可以看到

**Comment by YINGRJ** [comment]
我吐了 无法连接主机名

**Comment by minecraftxiaohu** [comment]
原因：我打开了腾讯课堂

**Comment by YINGRJ** [comment]
但是为什么我还能收到啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by YINGRJ** [comment]
暂时先在B站上聊（在b站回复）

**Comment by minecraftxiaohu** [comment]
不行！！！

**Comment by YINGRJ** [comment]
但是我会收到啊！

**Comment by YINGRJ** [comment]
我还能怎么办啊！

**Comment by YINGRJ** [comment]
你是要我死吗！

**Comment by minecraftxiaohu** [comment]
![image](https://user-images.githubusercontent.com/102411014/164369255-b8c4ac4d-ccdf-4612-8db1-58c664c3effb.png)
试试这样

**Comment by YINGRJ** [comment]
你再发一条消息试试看我会不会收到

**Comment by YINGRJ** [comment]
人呢

**Comment by minecraftxiaohu** [comment]
我的电脑已经成功被qq卡死
![image](https://user-images.githubusercontent.com/102411014/164369534-8939e80d-836d-47b9-8104-3917684c2832.png)
这个建议关掉

**Comment by minecraftxiaohu** [comment]
对了，手机上QQ邮件提醒里面也可以关闭

**Comment by minecraftxiaohu** [comment]
欸，人呢？该不会真出事了吧。

**Comment by YINGRJ** [comment]
怎么关

**Comment by YINGRJ** [comment]
手机上

**Comment by YINGRJ** [comment]
还有我还能收到消息c

**Comment by minecraftxiaohu** [comment]
手机QQ打开
给我看图片

**Comment by YINGRJ** [comment]
？

**Comment by minecraftxiaohu** [comment]
你QQ邮箱注册的GitHub对吧，那个QQ邮箱是谁的？是你的对吧。
那么，你把你手机QQ打开。
然后不是有个叫邮箱什么的东西吗，点开，截图给我

**Comment by YINGRJ** [comment]
在服务器里说

**Comment by minecraftxiaohu** [comment]
![image](https://user-images.githubusercontent.com/102411014/164371279-4815647c-9d21-41b5-9418-4ebab26e4271.png)
![image](https://user-images.githubusercontent.com/102411014/164371300-604a4245-8054-4c0c-9f7e-32247b6a3e0c.png)
![image](https://user-images.githubusercontent.com/102411014/164371330-817438a8-34a3-48b4-9109-ac06bc7d0610.png)
![image](https://user-images.githubusercontent.com/102411014/164371470-d04d3de6-f378-44b8-bd0e-69628f565f02.png)

**Comment by YINGRJ** [comment]
等一下
先别发消息！

**Comment by minecraftxiaohu** [comment]
![image](https://user-images.githubusercontent.com/102411014/164372042-ad7d34c7-d339-4426-8468-51224e622249.png)
这样试试

**Comment by minecraftxiaohu** [comment]
我发现你好像从来都不认真读消息，也不想去花时间捣鼓一些东西，而我却愿意去花时间弄。

**Comment by minecraftxiaohu** [comment]
看B站我发的消息

**Comment by minecraftxiaohu** [comment]
好了，现在你还会在别的地方弹邮件吗

**Comment by YINGRJ** [comment]
你再发一条消息试试

**Comment by minecraftxiaohu** [comment]
这是一条~~普通~~的消息，对吧&#91;doge&#93;

**Comment by YINGRJ** [comment]
电脑能收到

**Comment by YINGRJ** [comment]
手机没有

**Comment by YINGRJ** [comment]
成功了应该

**Comment by minecraftxiaohu** [comment]
呵呵
![image](https://user-images.githubusercontent.com/102411014/164420991-450539d1-8416-406b-aa09-e83bbc86780e.png)

**Comment by YINGRJ** [comment]
成功了应该

**Comment by minecraftxiaohu** [comment]
我无语了
![](https://user-images.githubusercontent.com/102411014/164420991-450539d1-8416-406b-aa09-e83bbc86780e.png)

**Comment by minecraftxiaohu** [comment]
不适宜内容：太吓人

**Comment by minecraftxiaohu** [comment]
不知道是谁举报的

**Comment by minecraftxiaohu** [comment]
我删除了那个视频

**Comment by YINGRJ** [comment]
无语 不就一个视频吗 玩不起 真的是

**Comment by YINGRJ** [comment]
举报什么啊

**Comment by minecraftxiaohu** [comment]
。。。
那个扬声器清灰的视频（嗯嗯啊啊啊啊啊）被人举报了
反正之前我就想删
结果这次真就有机会删了

**Comment by YINGRJ** [comment]
啊哈哈哈

**Comment by YINGRJ** [comment]
![image](https://user-images.githubusercontent.com/104064559/164422113-5e9eb52d-3fc9-4b81-956a-e8b89060570f.png)

**Comment by YINGRJ** [comment]
这是啥

**Comment by minecraftxiaohu** [comment]
同志，你现在可以往这里面上传文件了（每个文件不超过20MB）

**Comment by YINGRJ** [comment]
？哪个

**Comment by minecraftxiaohu** [comment]
不过最好是和代码什么有关的
不然GitHub就有点

**Comment by YINGRJ** [comment]
哦哦

**Comment by YINGRJ** [comment]
emm

**Comment by minecraftxiaohu** [comment]
对了，你没开摄像头

**Comment by YINGRJ** [comment]
对呀
我要看回放

**Comment by YINGRJ** [comment]
开了费电脑

**Comment by minecraftxiaohu** [comment]
。。。
看什么回放

**Comment by YINGRJ** [comment]
语文

**Comment by YINGRJ** [comment]
![image](https://user-images.githubusercontent.com/104064559/164422874-41cce425-c1c1-4881-9d83-c189cad5b32f.png)

**Comment by minecraftxiaohu** [comment]
。。

**Comment by minecraftxiaohu** [comment]
> 语文

我整节提高班都在看语文

**Comment by YINGRJ** [comment]
我上传这个[doge]

**Comment by minecraftxiaohu** [comment]
> 我上传这个[doge]

我表示你的某个部位似乎有问题

**Comment by YINGRJ** [comment]
doge

**Comment by YINGRJ** [comment]
我要编辑都编辑不了 记事本会卡死（未响应）

**Comment by minecraftxiaohu** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by minecraftxiaohu** [comment]
| 项目        | 价格   |  数量  |
| --------   | -----:  | :----:  |
| 计算机      | $1600   |   5     |
| 手机        |   $12   |   12   |
| 管线        |    $1    |  234  |

**Comment by minecraftxiaohu** [comment]
| 项目        | 价格   |  数量  |
| --------   | -----:  | :----:  |
| 计算机      | $114514   |   114514     |
| 手机        |   $1454   |   114514   |

**Comment by YINGRJ** [comment]
嗯？

**Comment by minecraftxiaohu** [comment]
怎么了

**Comment by YINGRJ** [comment]
你这是啥东西

**Comment by minecraftxiaohu** [comment]
表格啊

**Comment by minecraftxiaohu** [comment]
[新的真正的聊天地点](https://github.com/minecraftxiaohu/TalkAboutSomething/discussions/2)
